TARGET    := LED-BLINK

BUILD_DIR := ./Build

TOOLCHAIN  = arm-none-eabi-
CC  := $(TOOLCHAIN)gcc
CP  := $(TOOLCHAIN)objcopy
AS  := $(TOOLCHAIN)gcc -x assembler-with-cpp
SZ  := $(TOOLCHAIN)size
HEX := $(CP) -O ihex
BIN := $(CP) -O binary -S


DEFS := -D STM32F10X_HD  -D USE_STDPERIPH_DRIVER

LINK_SCRIPT := ./Linker/STM32F103ZETx_FLASH.ld

STARTUP_DIR := ./Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/gcc_ride7/
STARTUP_ASM := $(STARTUP_DIR)/startup_stm32f10x_hd.s

SRC_DIR := ./Libraries/CMSIS/
SRC_DIR += ./Libraries/CMSIS/CM3/CoreSupport/
SRC_DIR += ./Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/
SRC_DIR += ./Libraries/STM32F10x_StdPeriph_Driver/inc/
SRC_DIR += ./Libraries/STM32F10x_StdPeriph_Driver/src/
SRC_DIR += ./User/
SRC_DIR += ./User/led/



INC_DIR := $(addprefix -I,$(SRC_DIR))

C_SRC := $(wildcard $(addsuffix *.c,$(SRC_DIR)))
C_OBJ := $(addprefix $(BUILD_DIR)/,$(notdir $(C_SRC:.c=.o)))

ASM_SRC := $(wildcard $(addsuffix *.s,$(SRC_DIR)))
ASM_SRC += $(STARTUP_ASM)
ASM_OBJ := $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SRC:.s=.o)))


AS_FLAGS := $(INC_DIR) -mcpu=cortex-m3 -g -gdwarf-2 -mthumb -Os -Wall -fdata-sections -ffunction-sections -MMD -MP
CP_FLAGS := $(AS_FLAGS) $(DEFS)
LD_FLAGS := -mcpu=cortex-m3 -specs=nano.specs -T $(LINK_SCRIPT) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref,--gc-sections

vpath %.c $(SRC_DIR)
vpath %.s $(SRC_DIR) $(STARTUP_DIR)


.PRECIOUS: $(BUILD_DIR)/%.o




.PHONY: all
all: $(BUILD_DIR) $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).bin $(BUILD_DIR)/$(TARGET).hex
	$(SZ) $(BUILD_DIR)/$(TARGET).elf
	@du -sh $(BUILD_DIR)/$(TARGET).elf
	@du -sh $(BUILD_DIR)/$(TARGET).hex
	@du -sh $(BUILD_DIR)/$(TARGET).bin
	@echo "!!! DONE !!!"

$(BUILD_DIR)/%.o: %.c
	$(CC) -c $(CP_FLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s
	$(AS) -c $(AS_FLAGS) $< -o $@

$(BUILD_DIR)/%.elf: $(C_OBJ) $(ASM_OBJ) 
	$(CC) $(LD_FLAGS) $^ -o $@

%.hex: %.elf
	$(HEX) $< $@

%.bin: %.elf
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir -p $@




clean:
	rm $(BUILD_DIR) -rf

rebuild:
	make clean && make

st-flash:
	st-flash write $(BUILD_DIR)/$(TARGET).bin 0x8000000

isp-flash:
	stm32flash -b 115200 -i '-dtr&rts,dtr:-dtr&-rts,dtr' -v -w $(BUILD_DIR)/$(TARGET).bin /dev/ttyUSB0

isp-info:
	stm32flash -b 115200 -i '-dtr&rts,dtr:-dtr&-rts,dtr' /dev/ttyUSB0

st-erase:
	st-flash erase

isp-erase:
	stm32flash -b 115200 -i '-dtr&rts,dtr:-dtr&-rts,dtr' -o /dev/ttyUSB0


show:
	@echo $(C_SRC)
	@echo $(C_OBJ)
	@echo $(ASM_SRC)

# Include the .d makefiles which are generated by compiler
-include $(BUILD_DIR)/*.d
